SELECT OB.ORDERID,DM.BUSINESS,DM.Processflag
          FROM SVR_OP_BILLDATA OB, SVR_PUB_DA_MAINQUEUE DM 
         WHERE OB.MAINSN = DM.MAINSN
 
           AND DM.PROCESSFLAG<>'BOOKING'
        ORDER BY DM.RECEPTTIME;
        11111111111111111
